version: '3'

services:
  db:
    image: mongo
    ports:
      - '27017:27017'

  dbclient:
    image: mongoclient/mongoclient
    ports:
      - '3000:27016'
    depends_on:
      - db

  api:
    build:
      context: ./api
      args:
        - NODE_ENV=development
    env_file:
      - ./api/.env
    ports:
      - 1810:1810
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
